services:

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: lol_sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong_Password123!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  lol_api:
    container_name: lol_api
    build:
      context: .
      dockerfile: LoLProject.ApiService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # IMPORTANT : la ConnectionString que ton API attend
      ConnectionStrings__lolproject: "Server=lol_sql;Database=lolproject;User Id=sa;Password=YourStrong_Password123!;TrustServerCertificate=True;"
    ports:
      - "5284:8080"
    depends_on:
      - sql

  lol_webapp:
    container_name: lol_webapp
    build:
      context: .
      dockerfile: LoLProject.WebApp/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # URL du service API résolu par Docker (pas localhost !)
      services__apiservice__http__0: "http://lol_api:8080"
    ports:
      - "7209:8080"
    depends_on:
      - lol_api

volumes:
  sql_data:
