version: "3.9"

services:

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: lol_sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong_Password123!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  apiservice:
    container_name: lol_api
    build:
      context: .
      dockerfile: LoLProject.ApiService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Default: "Server=sql;Database=lolproject;User Id=sa;Password=YourStrong_Password123!;TrustServerCertificate=True;"
    ports:
      - "5284:8080"
    depends_on:
      - sql

  webapp:
    container_name: lol_webapp
    build:
      context: .
      dockerfile: LoLProject.WebApp/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      services__apiservice__http__0: "http://apiservice:8080"
    ports:
      - "7209:8080"
    depends_on:
      - apiservice

volumes:
  sql_data:
